services:
    client:
        build:
            context: .
            dockerfile: client/Dockerfile
            target: production
            args:
                - VITE_API_URL=${VITE_API_URL}
        container_name: pokedex-client
        restart: always
        env_file:
            - .env
        ports:
            - '3000:3000'
        networks:
            - app-network
        depends_on:
            - api

    api:
        build:
            context: .
            dockerfile: api/Dockerfile
            target: production
        container_name: pokedex-api
        restart: always
        env_file:
            - .env
        ports:
            - '${API_PORT}:${API_PORT}'
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        container_name: pokedex-db
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
